/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import java.awt.event.WindowAdapter;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Nuevo_Proveedor extends javax.swing.JPanel {

    /**
     * Creates new form Nuevo_Proveedor
     */
    public Nuevo_Proveedor() {
        initComponents();
    }

    public JButton getJBGuardarp() {
        return JBGuardarp;
    }

    public void setJBGuardarp(JButton JBGuardarp) {
        this.JBGuardarp = JBGuardarp;
    }

    public JComboBox<String> getjCSexop() {
        return jCSexop;
    }

    public void setjCSexop(JComboBox<String> jCSexop) {
        this.jCSexop = jCSexop;
    }

 
    public JButton getjBCancelarP() {
        return jBCancelarP;
    }

    public void setjBCancelarP(JButton jBCancelarP) {
        this.jBCancelarP = jBCancelarP;
    }

    public JLabel getLblCorreoP() {
        return lblCorreoP;
    }

    public void setLblCorreoP(JLabel lblCorreoP) {
        this.lblCorreoP = lblCorreoP;
    }

    public JLabel getLblDireccionp() {
        return lblDireccionp;
    }

    public void setLblDireccionp(JLabel lblDireccionp) {
        this.lblDireccionp = lblDireccionp;
    }

    public JLabel getLblNombrP() {
        return lblNombrP;
    }

    public void setLblNombrP(JLabel lblNombrP) {
        this.lblNombrP = lblNombrP;
    }

    public JLabel getLblProveedor() {
        return lblProveedor;
    }

    public void setLblProveedor(JLabel lblProveedor) {
        this.lblProveedor = lblProveedor;
    }

    public JLabel getLblSexo() {
        return lblSexo;
    }

    public void setLblSexo(JLabel lblSexo) {
        this.lblSexo = lblSexo;
    }

    public JLabel getLblTipodepersona() {
        return lblTipodepersona;
    }

    public void setLblTipodepersona(JLabel lblTipodepersona) {
        this.lblTipodepersona = lblTipodepersona;
    }

    public JLabel getLblfechadenacimiento() {
        return lblfechadenacimiento;
    }

    public void setLblfechadenacimiento(JLabel lblfechadenacimiento) {
        this.lblfechadenacimiento = lblfechadenacimiento;
    }

    public JTextField getTxtCorreop() {
        return txtCorreop;
    }

    public void setTxtCorreop(JTextField txtCorreop) {
        this.txtCorreop = txtCorreop;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public void setTxtDireccion(JTextField txtDireccion) {
        this.txtDireccion = txtDireccion;
    }

    public JTextField getTxtNombrep() {
        return txtNombrep;
    }

    public void setTxtNombrep(JTextField txtNombrep) {
        this.txtNombrep = txtNombrep;
    }

    public JTextField getTxtTelefonoP() {
        return txtTelefonoP;
    }

    public void setTxtTelefonoP(JTextField txtTelefonoP) {
        this.txtTelefonoP = txtTelefonoP;
    }

    public JComboBox<String> getJCDocumentop() {
        return JCDocumentop;
    }

    public void setJCDocumentop(JComboBox<String> JCDocumentop) {
        this.JCDocumentop = JCDocumentop;
    }

    public JLabel getJcdocumentop() {
        return jcdocumentop;
    }

    public void setJcdocumentop(JLabel jcdocumentop) {
        this.jcdocumentop = jcdocumentop;
    }

    public JDateChooser getjDfechap() {
        return jDfechap;
    }

    public void setjDfechap(JDateChooser jDfechap) {
        this.jDfechap = jDfechap;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblProveedor = new javax.swing.JLabel();
        jcdocumentop = new javax.swing.JLabel();
        JCDocumentop = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        lblNombrP = new javax.swing.JLabel();
        txtNombrep = new javax.swing.JTextField();
        lblCorreoP = new javax.swing.JLabel();
        txtCorreop = new javax.swing.JTextField();
        lblTelefoP = new javax.swing.JLabel();
        txtTelefonoP = new javax.swing.JTextField();
        lblDireccionp = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        lblTipodepersona = new javax.swing.JLabel();
        jCtipopersinap = new javax.swing.JComboBox<>();
        lblfechadenacimiento = new javax.swing.JLabel();
        jDfechap = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        JBGuardarp = new javax.swing.JButton();
        jBCancelarP = new javax.swing.JButton();
        jCSexop = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        lblProveedor.setForeground(new java.awt.Color(255, 102, 0));
        lblProveedor.setText("Proveedor");

        jcdocumentop.setText("Documento");

        JCDocumentop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione su documento", "Cedula", "Targeta", "otro" }));

        lblSexo.setText("Sexo");

        lblNombrP.setText("Nombre");

        lblCorreoP.setText("Correo");

        lblTelefoP.setText("Telefono");

        lblDireccionp.setText("Direccion");

        lblTipodepersona.setText("Tipo de persona");

        jCtipopersinap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Hombre", "Mujer", "Otro" }));

        lblfechadenacimiento.setText("fecha de nacimiento");

        JBGuardarp.setText("Guardar");

        jBCancelarP.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(JBGuardarp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBCancelarP)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBGuardarp)
                    .addComponent(jBCancelarP))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblProveedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombrP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCorreoP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTelefoP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTipodepersona)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblfechadenacimiento)
                                .addGap(18, 18, 18)
                                .addComponent(jDfechap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSexo)
                                    .addComponent(jcdocumentop))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JCDocumentop, 0, 242, Short.MAX_VALUE)
                                    .addComponent(txtNombrep, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCorreop, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCSexop, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDireccionp)
                                .addGap(67, 67, 67)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCtipopersinap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDireccion))))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProveedor)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCDocumentop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcdocumentop))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(jCSexop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrP)
                    .addComponent(txtNombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoP)
                    .addComponent(txtCorreop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefoP)
                    .addComponent(txtTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccionp)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipodepersona)
                    .addComponent(jCtipopersinap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblfechadenacimiento)
                    .addComponent(jDfechap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBGuardarp;
    private javax.swing.JComboBox<String> JCDocumentop;
    private javax.swing.JButton jBCancelarP;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCSexop;
    private javax.swing.JComboBox<String> jCtipopersinap;
    private com.toedter.calendar.JDateChooser jDfechap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jcdocumentop;
    private javax.swing.JLabel lblCorreoP;
    private javax.swing.JLabel lblDireccionp;
    private javax.swing.JLabel lblNombrP;
    private javax.swing.JLabel lblProveedor;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefoP;
    private javax.swing.JLabel lblTipodepersona;
    private javax.swing.JLabel lblfechadenacimiento;
    private javax.swing.JTextField txtCorreop;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombrep;
    private javax.swing.JTextField txtTelefonoP;
    // End of variables declaration//GEN-END:variables

}
