/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author SENA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public JButton getLblnuevo() {
        return lblnuevo;
    }

    public void setLblnuevo(JButton lblnuevo) {
        this.lblnuevo = lblnuevo;
    }

    public JButton getLblNuevo() {
        return lblNuevo;
    }

    public void setLblNuevo(JButton lblNuevo) {
        this.lblNuevo = lblNuevo;
    }

    public JButton getjBproveedorp() {
        return jBproveedorp;
    }

    public void setjBproveedorp(JButton jBproveedorp) {
        this.jBproveedorp = jBproveedorp;
    }

    public JTabbedPane getJdprincipal() {
        return jdproducto;
    }

    public void setJdprincipal(JTabbedPane jdprincipal) {
        this.jdproducto = jdprincipal;
    }

    public JTextField getTXTbuscar() {
        return TXTbuscar;
    }

    public void setTXTbuscar(JTextField TXTbuscar) {
        this.TXTbuscar = TXTbuscar;
    }

    public JPanel getJpUsuario() {
        return jpUsuario;
    }

    public void setJpUsuario(JPanel jpUsuario) {
        this.jpUsuario = jpUsuario;
    }

    public JTable getJTUSUARIO() {
        return JTUSUARIO;
    }

    public void setJTUSUARIO(JTable JTUSUARIO) {
        this.JTUSUARIO = JTUSUARIO;
    }

    public JTextField getTxtimg() {
        return Txtimg;
    }

    public void setTxtimg(JTextField Txtimg) {
        this.Txtimg = Txtimg;
    }

//    public JTextField getTxtnom() {
//        return Txtnom;
//    }
//
//    public void setTxtnom(JTextField Txtnom) {
//        this.Txtnom = Txtnom;
//    }
//
//    public JButton getJbGU() {
//        return JbGU;
//    }
//
//    public void setJbGU(JButton JbGU) {
//        this.JbGU = JbGU;
//    }
    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
//
//    public JTextField getTXTbus1() {
//        return TXTbus1;
//    }
//
//    public void setTXTbus1(JTextField TXTbus1) {
//        this.TXTbus1 = TXTbus1;
//    }

    public JButton getJBimg() {
        return JBimg;
    }

    public void setJBimg(JButton JBimg) {
        this.JBimg = JBimg;
    }

//    public JTextPane getTXTdescrip() {
//        return TXTdescrip;
//    }
//
//    public void setTXTdescrip(JTextPane TXTdescrip) {
//        this.TXTdescrip = TXTdescrip;
//    }
    public JTabbedPane getJdproducto() {
        return jdproducto;
    }

    public void setJdproducto(JTabbedPane jdproducto) {
        this.jdproducto = jdproducto;
    }

    public JTable getjTproducto() {
        return jTproducto;
    }

    public void setjTproducto(JTable jTproducto) {
        this.jTproducto = jTproducto;
    }

    public JTable getjTCliente() {
        return jTCliente;
    }

    public void setjTCliente(JTable jTCliente) {
        this.jTCliente = jTCliente;
    }

    public JTable getjTFactura() {
        return jTFactura;
    }

    public void setjTFactura(JTable jTFactura) {
        this.jTFactura = jTFactura;
    }

    public JTable getjTProveedor() {
        return jTProveedor;
    }

    public void setjTProveedor(JTable jTProveedor) {
        this.jTProveedor = jTProveedor;
    }

    public JTable getjTVentas() {
        return jTVentas;
    }

    public void setjTVentas(JTable jTVentas) {
        this.jTVentas = jTVentas;
    }

    public JButton getjBventas() {
        return jBventas;
    }

    public void setjBventas(JButton jBventas) {
        this.jBventas = jBventas;
    }

    public JButton getjBproducto() {
        return jBproducto;
    }

    public void setjBproducto(JButton jBproducto) {
        this.jBproducto = jBproducto;
    }

    public JButton getjBFactura() {
        return jBFactura;
    }

    public void setjBFactura(JButton jBFactura) {
        this.jBFactura = jBFactura;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btlupa = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jdproducto = new javax.swing.JTabbedPane();
        jpUsuario = new javax.swing.JPanel();
        lblnuevo = new javax.swing.JButton();
        TXTbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTUSUARIO = new javax.swing.JTable();
        jpcliente = new javax.swing.JPanel();
        lblNuevo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jPproveedor = new javax.swing.JPanel();
        jBproveedorp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTProveedor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jBventas = new javax.swing.JButton();
        jPfactura = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFactura = new javax.swing.JTable();
        jBFactura = new javax.swing.JButton();
        jPproducto = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTproducto = new javax.swing.JTable();
        lblimg = new javax.swing.JLabel();
        Txtimg = new javax.swing.JTextField();
        JBimg = new javax.swing.JButton();
        jBproducto = new javax.swing.JButton();
        lbltienda = new javax.swing.JLabel();

        Btlupa.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\lupa.png")); // NOI18N

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo.setText("Nuevo");

        JTUSUARIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTUSUARIO);

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addComponent(lblnuevo)
                .addGap(121, 121, 121)
                .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 524, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnuevo)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdproducto.addTab("Usuario", jpUsuario);

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        lblNuevo.setText("Nuevo cliente");

        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTCliente);

        javax.swing.GroupLayout jpclienteLayout = new javax.swing.GroupLayout(jpcliente);
        jpcliente.setLayout(jpclienteLayout);
        jpclienteLayout.setHorizontalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpclienteLayout.createSequentialGroup()
                        .addComponent(lblNuevo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpclienteLayout.setVerticalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jdproducto.addTab("Cliente", jpcliente);

        jBproveedorp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        jBproveedorp.setText("Nuevo proveedor");

        jTProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTProveedor);

        javax.swing.GroupLayout jPproveedorLayout = new javax.swing.GroupLayout(jPproveedor);
        jPproveedor.setLayout(jPproveedorLayout);
        jPproveedorLayout.setHorizontalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addComponent(jBproveedorp)
                .addGap(0, 785, Short.MAX_VALUE))
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        jPproveedorLayout.setVerticalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBproveedorp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jdproducto.addTab("proveedor", jPproveedor);

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTVentas);

        jBventas.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\agregar-usuario.png")); // NOI18N
        jBventas.setText("Nuevo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBventas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBventas)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jdproducto.addTab("Ventas", jPanel1);

        jTFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTFactura);

        jBFactura.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\agregar-usuario.png")); // NOI18N
        jBFactura.setText("Nuevo");

        javax.swing.GroupLayout jPfacturaLayout = new javax.swing.GroupLayout(jPfactura);
        jPfactura.setLayout(jPfacturaLayout);
        jPfacturaLayout.setHorizontalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBFactura)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPfacturaLayout.setVerticalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBFactura)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jdproducto.addTab("Factura", jPfactura);

        jTproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTproducto);

        lblimg.setText("Imagen");

        Txtimg.setEditable(false);

        JBimg.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\lupa.png")); // NOI18N

        jBproducto.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\agregar-usuario.png")); // NOI18N
        jBproducto.setText("Nuevo");

        javax.swing.GroupLayout jPproductoLayout = new javax.swing.GroupLayout(jPproducto);
        jPproducto.setLayout(jPproductoLayout);
        jPproductoLayout.setHorizontalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproductoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 905, Short.MAX_VALUE)
                    .addGroup(jPproductoLayout.createSequentialGroup()
                        .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBproducto)
                            .addGroup(jPproductoLayout.createSequentialGroup()
                                .addComponent(lblimg)
                                .addGap(45, 45, 45)
                                .addComponent(Txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(JBimg)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPproductoLayout.setVerticalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproductoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jBproducto)
                .addGap(57, 57, 57)
                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblimg)
                    .addComponent(Txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBimg))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(101, 101, 101))
        );

        jdproducto.addTab("Producto", jPproducto);

        lbltienda.setForeground(new java.awt.Color(255, 0, 0));
        lbltienda.setText("TIENDA COM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdproducto))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdproducto))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btlupa;
    private javax.swing.JButton JBimg;
    private javax.swing.JTable JTUSUARIO;
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JTextField Txtimg;
    private javax.swing.JButton jBFactura;
    private javax.swing.JButton jBproducto;
    private javax.swing.JButton jBproveedorp;
    private javax.swing.JButton jBventas;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPfactura;
    private javax.swing.JPanel jPproducto;
    private javax.swing.JPanel jPproveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTable jTFactura;
    private javax.swing.JTable jTProveedor;
    private javax.swing.JTable jTVentas;
    private javax.swing.JTable jTproducto;
    private javax.swing.JTabbedPane jdproducto;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JPanel jpcliente;
    private javax.swing.JButton lblNuevo;
    private javax.swing.JLabel lblimg;
    private javax.swing.JButton lblnuevo;
    private javax.swing.JLabel lbltienda;
    // End of variables declaration//GEN-END:variables

}
