/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author SENA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public JButton getLblnuevo() {
        return lblnuevo;
    }

    public void setLblnuevo(JButton lblnuevo) {
        this.lblnuevo = lblnuevo;
    }

    public JButton getLblNuevo() {
        return lblNuevo;
    }

    public void setLblNuevo(JButton lblNuevo) {
        this.lblNuevo = lblNuevo;
    }

    public JButton getjBproveedorp() {
        return jBproveedorp;
    }

    public void setjBproveedorp(JButton jBproveedorp) {
        this.jBproveedorp = jBproveedorp;
    }

    public JTabbedPane getJdprincipal() {
        return jdproducto;
    }

    public void setJdprincipal(JTabbedPane jdprincipal) {
        this.jdproducto = jdprincipal;
    }

    public JTextField getTXTbuscar() {
        return TXTbuscar;
    }

    public void setTXTbuscar(JTextField TXTbuscar) {
        this.TXTbuscar = TXTbuscar;
    }

    public JPanel getJpUsuario() {
        return jpUsuario;
    }

    public void setJpUsuario(JPanel jpUsuario) {
        this.jpUsuario = jpUsuario;
    }

    public JTable getJTUSUARIO() {
        return JTUSUARIO;
    }

    public void setJTUSUARIO(JTable JTUSUARIO) {
        this.JTUSUARIO = JTUSUARIO;
    }

    public JButton getLblnuevo11() {
        return lblnuevo11;
    }

    public void setLblnuevo11(JButton lblnuevo11) {
        this.lblnuevo11 = lblnuevo11;
    }

    public JTextField getTxtimg() {
        return Txtimg;
    }

    public void setTxtimg(JTextField Txtimg) {
        this.Txtimg = Txtimg;
    }

    public JTextField getTxtnom() {
        return Txtnom;
    }

    public void setTxtnom(JTextField Txtnom) {
        this.Txtnom = Txtnom;
    }

    public JButton getJbGU() {
        return JbGU;
    }

    public void setJbGU(JButton JbGU) {
        this.JbGU = JbGU;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JTextField getTXTbus1() {
        return TXTbus1;
    }

    public void setTXTbus1(JTextField TXTbus1) {
        this.TXTbus1 = TXTbus1;
    }

    public JButton getLblnuevo13() {
        return lblnuevo13;
    }

    public void setLblnuevo13(JButton lblnuevo13) {
        this.lblnuevo13 = lblnuevo13;
    }

    public JButton getJBimg() {
        return JBimg;
    }

    public void setJBimg(JButton JBimg) {
        this.JBimg = JBimg;
    }

    public JTextPane getTXTdescrip() {
        return TXTdescrip;
    }

    public void setTXTdescrip(JTextPane TXTdescrip) {
        this.TXTdescrip = TXTdescrip;
    }

    public JTabbedPane getJdproducto() {
        return jdproducto;
    }

    public void setJdproducto(JTabbedPane jdproducto) {
        this.jdproducto = jdproducto;
    }

    public JTable getjTproducto() {
        return jTproducto;
    }

    public void setjTproducto(JTable jTproducto) {
        this.jTproducto = jTproducto;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btlupa = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jdproducto = new javax.swing.JTabbedPane();
        jpUsuario = new javax.swing.JPanel();
        lblnuevo = new javax.swing.JButton();
        TXTbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTUSUARIO = new javax.swing.JTable();
        jpcliente = new javax.swing.JPanel();
        lblNuevo = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTCliente = new javax.swing.JTable();
        jPproveedor = new javax.swing.JPanel();
        jBproveedorp = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTProveedor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblnuevo11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTVentas = new javax.swing.JTable();
        jPfactura = new javax.swing.JPanel();
        lblnuevo12 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTFactura = new javax.swing.JTable();
        lblusuario = new javax.swing.JLabel();
        Txtusu = new javax.swing.JTextField();
        lblproveedor = new javax.swing.JLabel();
        Txtprovee = new javax.swing.JTextField();
        lbltipopago = new javax.swing.JLabel();
        JCpago = new javax.swing.JComboBox<>();
        lblnumerocomprobante = new javax.swing.JLabel();
        Txtcompro = new javax.swing.JTextField();
        JBguardar = new javax.swing.JButton();
        TxtBuscar = new javax.swing.JTextField();
        jPproducto = new javax.swing.JPanel();
        lblnuevo13 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTproducto = new javax.swing.JTable();
        lblnom = new javax.swing.JLabel();
        Txtnom = new javax.swing.JTextField();
        lblimg = new javax.swing.JLabel();
        Txtimg = new javax.swing.JTextField();
        lbldescripcion = new javax.swing.JLabel();
        JbGU = new javax.swing.JButton();
        TXTbus1 = new javax.swing.JTextField();
        JSdescripcion = new javax.swing.JScrollPane();
        TXTdescrip = new javax.swing.JTextPane();
        JBimg = new javax.swing.JButton();
        lbltienda = new javax.swing.JLabel();

        Btlupa.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\lupa.png")); // NOI18N

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo.setText("Nuevo");

        JTUSUARIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTUSUARIO);

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addComponent(lblnuevo)
                .addGap(121, 121, 121)
                .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 530, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 933, Short.MAX_VALUE)
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnuevo)
                    .addComponent(TXTbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jdproducto.addTab("Usuario", jpUsuario);

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        lblNuevo.setText("Nuevo cliente");

        jTCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTCliente);

        javax.swing.GroupLayout jpclienteLayout = new javax.swing.GroupLayout(jpcliente);
        jpcliente.setLayout(jpclienteLayout);
        jpclienteLayout.setHorizontalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpclienteLayout.createSequentialGroup()
                        .addComponent(lblNuevo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpclienteLayout.setVerticalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jdproducto.addTab("Cliente", jpcliente);

        jBproveedorp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        jBproveedorp.setText("Nuevo proveedor");

        jTProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(jTProveedor);

        javax.swing.GroupLayout jPproveedorLayout = new javax.swing.GroupLayout(jPproveedor);
        jPproveedor.setLayout(jPproveedorLayout);
        jPproveedorLayout.setHorizontalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addComponent(jBproveedorp)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPproveedorLayout.setVerticalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBproveedorp)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jdproducto.addTab("proveedor", jPproveedor);

        lblnuevo11.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo11.setText("Nuevo");

        jTVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTVentas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblnuevo11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblnuevo11)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jdproducto.addTab("Ventas", jPanel1);

        lblnuevo12.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo12.setText("Nuevo");

        jTFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTFactura);

        lblusuario.setText("Usuario");

        lblproveedor.setText("Proveedor");

        lbltipopago.setText("Tipo de pago");

        JCpago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione.....", "Efectivo", "Targeta", "Otro" }));

        lblnumerocomprobante.setText("Numero de comprobante");

        JBguardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\disco.png")); // NOI18N
        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        TxtBuscar.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        TxtBuscar.setText("Buscar");

        javax.swing.GroupLayout jPfacturaLayout = new javax.swing.GroupLayout(jPfactura);
        jPfactura.setLayout(jPfacturaLayout);
        jPfacturaLayout.setHorizontalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addComponent(lblnuevo12)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPfacturaLayout.createSequentialGroup()
                        .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPfacturaLayout.createSequentialGroup()
                                .addComponent(lblproveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txtprovee))
                            .addGroup(jPfacturaLayout.createSequentialGroup()
                                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnumerocomprobante)
                            .addComponent(lbltipopago))
                        .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPfacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txtcompro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 292, Short.MAX_VALUE))
                            .addGroup(jPfacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBguardar)
                                .addGap(17, 17, 17))
                            .addGroup(jPfacturaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(JCpago, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPfacturaLayout.setVerticalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPfacturaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblnuevo12)
                .addGap(21, 21, 21)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario)
                    .addComponent(Txtusu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltipopago)
                    .addComponent(JCpago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblproveedor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Txtprovee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblnumerocomprobante)
                        .addComponent(Txtcompro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBguardar)))
                .addGap(18, 18, 18)
                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jdproducto.addTab("Factura", jPfactura);

        lblnuevo13.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo13.setText("Nuevo");

        jTproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTproducto);

        lblnom.setText("Nombre");

        lblimg.setText("Imagen");

        Txtimg.setEditable(false);

        lbldescripcion.setText("Descripcion");

        JbGU.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\disco.png")); // NOI18N
        JbGU.setText("Guardar");

        JSdescripcion.setViewportView(TXTdescrip);

        JBimg.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\lupa.png")); // NOI18N

        javax.swing.GroupLayout jPproductoLayout = new javax.swing.GroupLayout(jPproducto);
        jPproducto.setLayout(jPproductoLayout);
        jPproductoLayout.setHorizontalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproductoLayout.createSequentialGroup()
                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnuevo13)
                    .addGroup(jPproductoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPproductoLayout.createSequentialGroup()
                                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblnom, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblimg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Txtnom)
                                    .addComponent(Txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbldescripcion)
                                    .addComponent(JBimg))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JSdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(JbGU))
                            .addComponent(jScrollPane4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPproductoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TXTbus1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPproductoLayout.setVerticalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproductoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblnuevo13)
                .addGap(23, 23, 23)
                .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPproductoLayout.createSequentialGroup()
                        .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnom)
                            .addComponent(Txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldescripcion))
                        .addGap(34, 34, 34)
                        .addGroup(jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblimg)
                            .addComponent(Txtimg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBimg)))
                    .addGroup(jPproductoLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(JbGU))
                    .addComponent(JSdescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(TXTbus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jdproducto.addTab("Producto", jPproducto);

        lbltienda.setForeground(new java.awt.Color(255, 0, 0));
        lbltienda.setText("TIENDA COM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jdproducto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdproducto))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBguardarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btlupa;
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBimg;
    private javax.swing.JComboBox<String> JCpago;
    private javax.swing.JScrollPane JSdescripcion;
    private javax.swing.JTable JTUSUARIO;
    private javax.swing.JButton JbGU;
    private javax.swing.JTextField TXTbus1;
    private javax.swing.JTextField TXTbuscar;
    private javax.swing.JTextPane TXTdescrip;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField Txtcompro;
    private javax.swing.JTextField Txtimg;
    private javax.swing.JTextField Txtnom;
    private javax.swing.JTextField Txtprovee;
    private javax.swing.JTextField Txtusu;
    private javax.swing.JButton jBproveedorp;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPfactura;
    private javax.swing.JPanel jPproducto;
    private javax.swing.JPanel jPproveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTCliente;
    private javax.swing.JTable jTFactura;
    private javax.swing.JTable jTProveedor;
    private javax.swing.JTable jTVentas;
    private javax.swing.JTable jTproducto;
    private javax.swing.JTabbedPane jdproducto;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JPanel jpcliente;
    private javax.swing.JButton lblNuevo;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblnom;
    private javax.swing.JButton lblnuevo;
    private javax.swing.JButton lblnuevo11;
    private javax.swing.JButton lblnuevo12;
    private javax.swing.JButton lblnuevo13;
    private javax.swing.JLabel lblnumerocomprobante;
    private javax.swing.JLabel lblproveedor;
    private javax.swing.JLabel lbltienda;
    private javax.swing.JLabel lbltipopago;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables

}
