/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;

/**
 *
 * @author SENA
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    public JButton getLblnuevo() {
        return lblnuevo;
    }

    public void setLblnuevo(JButton lblnuevo) {
        this.lblnuevo = lblnuevo;
    }

    public JButton getLblNuevo() {
        return lblNuevo;
    }

    public void setLblNuevo(JButton lblNuevo) {
        this.lblNuevo = lblNuevo;
    }

    public JButton getjBproveedorp() {
        return jBproveedorp;
    }

    public void setjBproveedorp(JButton jBproveedorp) {
        this.jBproveedorp = jBproveedorp;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdprincipal = new javax.swing.JTabbedPane();
        jpUsuario = new javax.swing.JPanel();
        lblnuevo = new javax.swing.JButton();
        jpcliente = new javax.swing.JPanel();
        lblNuevo = new javax.swing.JButton();
        jPproveedor = new javax.swing.JPanel();
        jBproveedorp = new javax.swing.JButton();
        jPproducto = new javax.swing.JPanel();
        jPfactura = new javax.swing.JPanel();
        lbltienda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblnuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\SENA\\Documents\\NetBeansProjects\\tienda_com\\src\\main\\resources\\img\\intimidad.png")); // NOI18N
        lblnuevo.setText("Nuevo");

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addComponent(lblnuevo)
                .addGap(0, 360, Short.MAX_VALUE))
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblnuevo)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jdprincipal.addTab("Usuario", jpUsuario);

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        lblNuevo.setText("Nuevo cliente");

        javax.swing.GroupLayout jpclienteLayout = new javax.swing.GroupLayout(jpcliente);
        jpcliente.setLayout(jpclienteLayout);
        jpclienteLayout.setHorizontalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNuevo)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        jpclienteLayout.setVerticalGroup(
            jpclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpclienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNuevo)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jdprincipal.addTab("Cliente", jpcliente);

        jBproveedorp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/intimidad.png"))); // NOI18N
        jBproveedorp.setText("Nuevo proveedor");

        javax.swing.GroupLayout jPproveedorLayout = new javax.swing.GroupLayout(jPproveedor);
        jPproveedor.setLayout(jPproveedorLayout);
        jPproveedorLayout.setHorizontalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addComponent(jBproveedorp)
                .addGap(0, 303, Short.MAX_VALUE))
        );
        jPproveedorLayout.setVerticalGroup(
            jPproveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPproveedorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jBproveedorp)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jdprincipal.addTab("proveedor", jPproveedor);

        javax.swing.GroupLayout jPproductoLayout = new javax.swing.GroupLayout(jPproducto);
        jPproducto.setLayout(jPproductoLayout);
        jPproductoLayout.setHorizontalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPproductoLayout.setVerticalGroup(
            jPproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jdprincipal.addTab("Producto", jPproducto);

        javax.swing.GroupLayout jPfacturaLayout = new javax.swing.GroupLayout(jPfactura);
        jPfactura.setLayout(jPfacturaLayout);
        jPfacturaLayout.setHorizontalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPfacturaLayout.setVerticalGroup(
            jPfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jdprincipal.addTab("Factura", jPfactura);

        lbltienda.setText("TIENDA COM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltienda, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jdprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBproveedorp;
    private javax.swing.JPanel jPfactura;
    private javax.swing.JPanel jPproducto;
    private javax.swing.JPanel jPproveedor;
    private javax.swing.JTabbedPane jdprincipal;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JPanel jpcliente;
    private javax.swing.JButton lblNuevo;
    private javax.swing.JButton lblnuevo;
    private javax.swing.JLabel lbltienda;
    // End of variables declaration//GEN-END:variables

}
